development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  YELP_CONSUMER_KEY: <%= ENV["YELP_CONSUMER_KEY"] %>
  YELP_CONSUMER_SECRET: <%= ENV["YELP_CONSUMER_SECRET"] %>
  YELP_TOKEN: <%= ENV["YELP_TOKEN"] %>
  YELP_TOKEN_SECRET: <%= ENV["YELP_TOKEN_SECRET"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  YELP_CONSUMER_KEY: <%= ENV["YELP_CONSUMER_KEY"] %>
  YELP_CONSUMER_SECRET: <%= ENV["YELP_CONSUMER_SECRET"] %>
  YELP_TOKEN: <%= ENV["YELP_TOKEN"] %>
  YELP_TOKEN_SECRET: <%= ENV["YELP_TOKEN_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  YELP_CONSUMER_KEY: <%= ENV["YELP_CONSUMER_KEY"] %>
  YELP_CONSUMER_SECRET: <%= ENV["YELP_CONSUMER_SECRET"] %>
  YELP_TOKEN: <%= ENV["YELP_TOKEN"] %>
  YELP_TOKEN_SECRET: <%= ENV["YELP_TOKEN_SECRET"] %>
