development:
  secret_key_base: 8383b9ccd3b79e4d775a11bdf729aabf8bda6abcdacc28bfb166ba2e011af3ce76f43d4cfa7217ddc0b4146a365a86c4e8de95e1bd0cda9bdb299e8588f80e8d
  YELP_CONSUMER_KEY: GxZyK4zz5kqfInydieSooQ
  YELP_CONSUMER_SECRET: _HsZeS6t8s9kG_xtutYumrg4ogw
  YELP_TOKEN: ShO4FzIB8LWsqve4ItdhzBCz7gP8GzYB
  YELP_TOKEN_SECRET: n4waUAkGQd2DRZksXGKfuhUltlE

test:
  secret_key_base: 3f5d83ebd8a7b1814a62faed963939c2eb86785fee35ff7e0601637dfd0203bfdd71d56b21a003e7f3b7688762801bae642f55780400501a641c819aa916d590
  YELP_CONSUMER_KEY: GxZyK4zz5kqfInydieSooQ
  YELP_CONSUMER_SECRET: _HsZeS6t8s9kG_xtutYumrg4ogw
  YELP_TOKEN: ShO4FzIB8LWsqve4ItdhzBCz7gP8GzYB
  YELP_TOKEN_SECRET: n4waUAkGQd2DRZksXGKfuhUltlE
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  YELP_CONSUMER_KEY: GxZyK4zz5kqfInydieSooQ
  YELP_CONSUMER_SECRET: _HsZeS6t8s9kG_xtutYumrg4ogw
  YELP_TOKEN: ShO4FzIB8LWsqve4ItdhzBCz7gP8GzYB
  YELP_TOKEN_SECRET: n4waUAkGQd2DRZksXGKfuhUltlE